# Site settings
baseurl = "/"
languageCode = "en-us"
title = "ET | Portfolio"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    name = "Eric Talviste"
    description = "This is my porftolio page to show off my works!"

    email = "eric.talviste@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "ET | Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Eric Talviste"
        subtitle = "Developer - Designer - Musician"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"
        subtitle_design = "Designs"
        subtitle_programs = "Programs"

        [params.portfolio.modal]
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I have a degree in junior software development and have been working on development for a solid 2 years. My portfolio includes languages such as C#, python and additionally many web-development libraries and frameworks."
        right = "Besides software and web-development, I also love different kinds of Art-work. My art aspirations span wall to wall from designing posters, logos and adverts. To writing movie-scenes. Additionally I love creating and writing music aswell."

        [params.about.button]
            text = "Check out my CV here!"
            link = "./EricTalvisteCV_EN.pdf"
            icon = "download"

    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Estonia", "Tallinn, Harjumaa"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/EricTalv"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "https://www.linkedin.com/in/erictalviste/"
