# Site settings
baseurl = "4154ea2c.ngrok.io"
languageCode = "en-us"
title = "Eric Talviste | Portfolio"

googleAnalytics = "UA-166928853-2"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    name = "Eric Talviste"
    description = "This is Eric Talviste's Portfolio website"

    email = "eric.talviste@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = [ "js/myJS.js" ]

    [params.navigation]
        brand = "ET | Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Eric Talviste"
        subtitle = "Developer - Designer - Musician"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"
        subtitle_design = "Designs"
        subtitle_programs = "Programs"

        [params.portfolio.modal]
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Hi there! My names Eric, I am what you would call a Junior Artsy/IT-tech person, I havent quite settled with one or the other so I am kinda dabbeling in everything! Degree wise so far I have studied software development for 3 years and dabbled in the programming world on my own on the side."
        right = "I wouldn't consider myself an avarage text-book-study-type-person, rather I find my ambitions lie many steps ahead of me, this causes alot of frustration BUT enables me to stay curious and keep on finding new and exciting challenges. So if you are an Employer, A curious pete, an Ambitous teen but have an Idea worth a while, then write me a letter and I'll surely be interested! c: "

        [params.about.button]
            text = "Check out my CV here!"
            link = "./EricTalvisteCV_EN.pdf"
            icon = "download"

    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Estonia", "Tallinn, Harjumaa"]

        [params.footer.email]
            title = "Or contact me straight"

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/EricTalv"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "https://www.linkedin.com/in/erictalviste/"

            [[params.footer.social.networks]]
                icon = "fa-dribbble"
                link=  "https://dribbble.com/EricTalv"

        	[[params.footer.social.networks]]
                icon = "fal fa-dove"
                link=  "http://etxp.tk"
